# Generated by Django 3.1.3 on 2021-03-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='phone_number',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
